/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBulkRenewal,
  IBulkRenewalInterface,
} from "../../../src/iotxregistrar/IBulkRenewal";

const _abi = [
  {
    inputs: [
      {
        internalType: "string[]",
        name: "names",
        type: "string[]",
      },
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
    ],
    name: "renewAll",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string[]",
        name: "names",
        type: "string[]",
      },
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
    ],
    name: "rentPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "total",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBulkRenewal__factory {
  static readonly abi = _abi;
  static createInterface(): IBulkRenewalInterface {
    return new utils.Interface(_abi) as IBulkRenewalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBulkRenewal {
    return new Contract(address, _abi, signerOrProvider) as IBulkRenewal;
  }
}
