/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  TestResolver,
  TestResolverInterface,
} from "../../../src/iotxregistrar/TestResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
    ],
    name: "addr",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_node",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "setAddr",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceID",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102a6806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806301ffc9a7146100465780633b3b57de1461006e578063d5fa2b00146100c9575b600080fd5b6100596100543660046101c5565b61012c565b60405190151581526020015b60405180910390f35b6100a461007c36600461020e565b60009081526020819052604090205473ffffffffffffffffffffffffffffffffffffffff1690565b60405173ffffffffffffffffffffffffffffffffffffffff9091168152602001610065565b61012a6100d7366004610227565b60009182526020829052604090912080547fffffffffffffffffffffffff00000000000000000000000000000000000000001673ffffffffffffffffffffffffffffffffffffffff909216919091179055565b005b60007f01ffc9a7000000000000000000000000000000000000000000000000000000007fffffffff00000000000000000000000000000000000000000000000000000000831614806101bf57507f3b3b57de000000000000000000000000000000000000000000000000000000007fffffffff000000000000000000000000000000000000000000000000000000008316145b92915050565b6000602082840312156101d757600080fd5b81357fffffffff000000000000000000000000000000000000000000000000000000008116811461020757600080fd5b9392505050565b60006020828403121561022057600080fd5b5035919050565b6000806040838503121561023a57600080fd5b82359150602083013573ffffffffffffffffffffffffffffffffffffffff8116811461026557600080fd5b80915050925092905056fea2646970667358221220cb01ae9c1485a782f3d4b5dae08dd4359791472f3ae923051a2ca94a8d77bfb064736f6c63430008110033";

type TestResolverConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestResolverConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TestResolver__factory extends ContractFactory {
  constructor(...args: TestResolverConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<TestResolver> {
    return super.deploy(overrides || {}) as Promise<TestResolver>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): TestResolver {
    return super.attach(address) as TestResolver;
  }
  override connect(signer: Signer): TestResolver__factory {
    return super.connect(signer) as TestResolver__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestResolverInterface {
    return new utils.Interface(_abi) as TestResolverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestResolver {
    return new Contract(address, _abi, signerOrProvider) as TestResolver;
  }
}
