/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155ReceiverMock__factory } from "./ERC1155ReceiverMock__factory";
export { TestUnwrap__factory } from "./TestUnwrap__factory";
export { UpgradedNameWrapperMock__factory } from "./UpgradedNameWrapperMock__factory";
