/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155ReceiverMock } from "./ERC1155ReceiverMock";
export type { TestUnwrap } from "./TestUnwrap";
export type { UpgradedNameWrapperMock } from "./UpgradedNameWrapperMock";
