/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { INS__factory } from "./INS__factory";
export { INSRegistry__factory } from "./INSRegistry__factory";
