/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as reverseRegistrarSol from "./ReverseRegistrar.sol";
export type { reverseRegistrarSol };
export type { IReverseRegistrar } from "./IReverseRegistrar";
export type { ReverseClaimer } from "./ReverseClaimer";
