/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iotxregistrar from "./iotxregistrar";
export * as registry from "./registry";
export * as resolvers from "./resolvers";
export * as reverseRegistrar from "./reverseRegistrar";
export * as root from "./root";
export * as utils from "./utils";
export * as wrapper from "./wrapper";
