/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as universalResolverSol from "./UniversalResolver.sol";
export type { universalResolverSol };
export type { ERC20Recoverable } from "./ERC20Recoverable";
export type { TestHexUtils } from "./TestHexUtils";
export type { TestNameEncoder } from "./TestNameEncoder";
