/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface TestHexUtilsInterface extends utils.Interface {
  functions: {
    "hexStringToBytes32(bytes,uint256,uint256)": FunctionFragment;
    "hexToAddress(bytes,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "hexStringToBytes32" | "hexToAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "hexStringToBytes32",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hexToAddress",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "hexStringToBytes32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hexToAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TestHexUtils extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestHexUtilsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    hexStringToBytes32(
      name: PromiseOrValue<BytesLike>,
      idx: PromiseOrValue<BigNumberish>,
      lastInx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, boolean]>;

    hexToAddress(
      input: PromiseOrValue<BytesLike>,
      idx: PromiseOrValue<BigNumberish>,
      lastInx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, boolean]>;
  };

  hexStringToBytes32(
    name: PromiseOrValue<BytesLike>,
    idx: PromiseOrValue<BigNumberish>,
    lastInx: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, boolean]>;

  hexToAddress(
    input: PromiseOrValue<BytesLike>,
    idx: PromiseOrValue<BigNumberish>,
    lastInx: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, boolean]>;

  callStatic: {
    hexStringToBytes32(
      name: PromiseOrValue<BytesLike>,
      idx: PromiseOrValue<BigNumberish>,
      lastInx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, boolean]>;

    hexToAddress(
      input: PromiseOrValue<BytesLike>,
      idx: PromiseOrValue<BigNumberish>,
      lastInx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, boolean]>;
  };

  filters: {};

  estimateGas: {
    hexStringToBytes32(
      name: PromiseOrValue<BytesLike>,
      idx: PromiseOrValue<BigNumberish>,
      lastInx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hexToAddress(
      input: PromiseOrValue<BytesLike>,
      idx: PromiseOrValue<BigNumberish>,
      lastInx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    hexStringToBytes32(
      name: PromiseOrValue<BytesLike>,
      idx: PromiseOrValue<BigNumberish>,
      lastInx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hexToAddress(
      input: PromiseOrValue<BytesLike>,
      idx: PromiseOrValue<BigNumberish>,
      lastInx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
