/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BatchGateway__factory } from "./BatchGateway__factory";
export { UniversalResolver__factory } from "./UniversalResolver__factory";
