/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
import type * as profiles from "./profiles";
export type { profiles };
export type { IMulticallable } from "./IMulticallable";
export type { Multicallable } from "./Multicallable";
export type { OwnedResolver } from "./OwnedResolver";
export type { PublicResolver } from "./PublicResolver";
export type { Resolver } from "./Resolver";
export type { ResolverBase } from "./ResolverBase";
