/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BatchGateway } from "./BatchGateway";
export type { UniversalResolver } from "./UniversalResolver";
