/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as universalResolverSol from "./UniversalResolver.sol";
export { ERC20Recoverable__factory } from "./ERC20Recoverable__factory";
export { TestHexUtils__factory } from "./TestHexUtils__factory";
export { TestNameEncoder__factory } from "./TestNameEncoder__factory";
