/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NameResolver } from "./NameResolver";
export type { ReverseRegistrar } from "./ReverseRegistrar";
