/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Controllable } from "./Controllable";
export type { Ownable } from "./Ownable";
export type { Root } from "./Root";
