/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IExtendedDNSResolver,
  IExtendedDNSResolverInterface,
} from "../../../../src/resolvers/profiles/IExtendedDNSResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "name",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "context",
        type: "bytes",
      },
    ],
    name: "resolve",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IExtendedDNSResolver__factory {
  static readonly abi = _abi;
  static createInterface(): IExtendedDNSResolverInterface {
    return new utils.Interface(_abi) as IExtendedDNSResolverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExtendedDNSResolver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IExtendedDNSResolver;
  }
}
