/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stablePriceOracleSol from "./StablePriceOracle.sol";
export type { stablePriceOracleSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { BaseRegistrarImplementation } from "./BaseRegistrarImplementation";
export type { BulkRenewal } from "./BulkRenewal";
export type { DummyOracle } from "./DummyOracle";
export type { ExponentialPremiumPriceOracle } from "./ExponentialPremiumPriceOracle";
export type { IBaseRegistrar } from "./IBaseRegistrar";
export type { IBulkRenewal } from "./IBulkRenewal";
export type { IIOTXRegistrarController } from "./IIOTXRegistrarController";
export type { ILinearPremiumPriceOracle } from "./ILinearPremiumPriceOracle";
export type { INameChecker } from "./INameChecker";
export type { IOTXRegistrarController } from "./IOTXRegistrarController";
export type { IPriceOracle } from "./IPriceOracle";
export type { LinearPremiumPriceOracle } from "./LinearPremiumPriceOracle";
export type { StaticBulkRenewal } from "./StaticBulkRenewal";
export type { TestResolver } from "./TestResolver";
export type { ZeroWidthNameChecker } from "./ZeroWidthNameChecker";
