/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { NameResolver__factory } from "./NameResolver__factory";
export { ReverseRegistrar__factory } from "./ReverseRegistrar__factory";
