/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iotxregistrar from "./iotxregistrar";
export type { iotxregistrar };
import type * as registry from "./registry";
export type { registry };
import type * as resolvers from "./resolvers";
export type { resolvers };
import type * as reverseRegistrar from "./reverseRegistrar";
export type { reverseRegistrar };
import type * as root from "./root";
export type { root };
import type * as utils from "./utils";
export type { utils };
import type * as wrapper from "./wrapper";
export type { wrapper };
